// <auto-generated />
using System;
using ChacourShop.ProductAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ChacourShop.ProductAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210707170800_AddedProductDataToProductModelToDb")]
    partial class AddedProductDataToProductModelToDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ChacourShop.ProductAPI.Models.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ProductCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockLevel")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("c193627d-a3a3-4da7-b7d9-4df623d176f4"),
                            CategoryName = "Pommade",
                            CreateDate = new DateTime(2021, 7, 7, 17, 8, 0, 325, DateTimeKind.Local).AddTicks(714),
                            Description = "Glutathione Extra Fort White Body Soap Resultat 5jr.",
                            Price = 2500.0,
                            ProductCode = "P0001",
                            ProductImage = "http://chacour.shop/ChacourCosmeticAPI/LogoImg/PI9VKTI027CQK8I.jpg",
                            ProductName = "SAVON GLUTA EXTRA FORT",
                            StockLevel = 100,
                            UserId = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                        },
                        new
                        {
                            ProductId = new Guid("cbdea814-f1b1-4a5a-9c95-abe8e22f1577"),
                            CategoryName = "Pommade",
                            CreateDate = new DateTime(2021, 7, 7, 17, 8, 0, 328, DateTimeKind.Local).AddTicks(7915),
                            Description = "Concentre Glutathione Extra Fort Actif Intence Eclaircissant Propriete.",
                            Price = 12000.0,
                            ProductCode = "P0002",
                            ProductImage = "http://chacour.shop/ChacourCosmeticAPI/LogoImg/CI3ETKF5869E40Y.jpg",
                            ProductName = "LAIT GLUTATHIONE",
                            StockLevel = 100,
                            UserId = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                        },
                        new
                        {
                            ProductId = new Guid("a580858b-aaad-43d5-ac53-264ef21bea52"),
                            CategoryName = "Pommade",
                            CreateDate = new DateTime(2021, 7, 7, 17, 8, 0, 328, DateTimeKind.Local).AddTicks(8081),
                            Description = "Lait de beaute eclaircissant, Hydratant et nourissant. A base de plantes, d'huiles essentielles et de vitamines.",
                            Price = 7000.0,
                            ProductCode = "P0003",
                            ProductImage = "http://chacour.shop/ChacourCosmeticAPI/LogoImg/BLLEP02KFQY18EY.jpg",
                            ProductName = "LAIT FINAL JAUNE",
                            StockLevel = 100,
                            UserId = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                        },
                        new
                        {
                            ProductId = new Guid("d0f3b59a-a1a1-4ab0-8d17-17c9fe8550e1"),
                            CategoryName = "Pommade",
                            CreateDate = new DateTime(2021, 7, 7, 17, 8, 0, 328, DateTimeKind.Local).AddTicks(8105),
                            Description = "Eclaircissant pour le soin corporel.",
                            Price = 7000.0,
                            ProductCode = "P0004",
                            ProductImage = "http://chacour.shop/ChacourCosmeticAPI/LogoImg/1T5QCV1I1OJ8EG3.jpg",
                            ProductName = "LAIT KOJIC ACID ROUGE",
                            StockLevel = 100,
                            UserId = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                        },
                        new
                        {
                            ProductId = new Guid("c9744f4b-435b-4924-8cd4-e8485b1daab3"),
                            CategoryName = "Pommade",
                            CreateDate = new DateTime(2021, 7, 7, 17, 8, 0, 328, DateTimeKind.Local).AddTicks(8124),
                            Description = "Concentre Glutathione Extra Fort Actif Intence Eclaircissant Propriete.",
                            Price = 6000.0,
                            ProductCode = "P0005",
                            ProductImage = "http://chacour.shop/ChacourCosmeticAPI/LogoImg/JAZO5N2IOXIHGDP.jpg",
                            ProductName = "CONCENTRE GLUTA BLEU",
                            StockLevel = 100,
                            UserId = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                        },
                        new
                        {
                            ProductId = new Guid("13d7744c-f6b8-4802-8eef-8973713a4a98"),
                            CategoryName = "Pommade",
                            CreateDate = new DateTime(2021, 7, 7, 17, 8, 0, 328, DateTimeKind.Local).AddTicks(8148),
                            Description = "Light Ultra Soft. Lait super eclaircissant aux bio-vegetaux.",
                            Price = 9000.0,
                            ProductCode = "P0006",
                            ProductImage = "http://chacour.shop/ChacourCosmeticAPI/LogoImg/DF4FAL2M74H0MMO.jpg",
                            ProductName = "LAIT B LIGHT",
                            StockLevel = 100,
                            UserId = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                        },
                        new
                        {
                            ProductId = new Guid("c7cee65a-378b-4057-bfdc-6db0ecadab96"),
                            CategoryName = "Pommade",
                            CreateDate = new DateTime(2021, 7, 7, 17, 8, 0, 328, DateTimeKind.Local).AddTicks(8176),
                            Description = "X2 AHA White Body Soap Resultat 5jr. Special formula for face & body with Glutathione, Collagen, Alpha-Arbutin, plus Vit. C & E.",
                            Price = 2500.0,
                            ProductCode = "P0007",
                            ProductImage = "http://chacour.shop/ChacourCosmeticAPI/LogoImg/9UGR4D92YF0GH8F.jpg",
                            ProductName = "SAVON AHA",
                            StockLevel = 100,
                            UserId = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                        },
                        new
                        {
                            ProductId = new Guid("dfbfcb15-dad4-41af-966f-0f55517bfee2"),
                            CategoryName = "Pommade",
                            CreateDate = new DateTime(2021, 7, 7, 17, 8, 0, 328, DateTimeKind.Local).AddTicks(8194),
                            Description = "Whitening Creamy Foam Shower Mousse Sacred Lotus. Lotus Sacre. Whitening Exfolient and Scrubed. Creme douche Eclaircissante a la mousse de coton 750ml.",
                            Price = 6000.0,
                            ProductCode = "P0008",
                            ProductImage = "http://chacour.shop/ChacourCosmeticAPI/LogoImg/RQV2490QW7GHIWJ.jpg",
                            ProductName = "GEL DOUCHE FINAL",
                            StockLevel = 100,
                            UserId = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                        },
                        new
                        {
                            ProductId = new Guid("4efedf0c-27b0-4ff6-8e0e-c0d0eb73bf7f"),
                            CategoryName = "Pommade",
                            CreateDate = new DateTime(2021, 7, 7, 17, 8, 0, 328, DateTimeKind.Local).AddTicks(8211),
                            Description = "Nouvelle pommade.",
                            Price = 5000.0,
                            ProductCode = "P0009",
                            ProductImage = "http://chacour.shop/ChacourCosmeticAPI/LogoImg/PAR161XYEHCBWLF.jpg",
                            ProductName = "LOTION NEW SKIN",
                            StockLevel = 100,
                            UserId = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                        },
                        new
                        {
                            ProductId = new Guid("a2c43b55-313d-4eb3-a554-e26f510a15f2"),
                            CategoryName = "Pommade",
                            CreateDate = new DateTime(2021, 7, 7, 17, 8, 0, 328, DateTimeKind.Local).AddTicks(8237),
                            Description = "Extra fort lait tonifiant, actif intense eclaircissant. Exclusive strong milk, toning milk, active intense. Advanced lightning fadoul.",
                            Price = 8000.0,
                            ProductCode = "P0010",
                            ProductImage = "http://chacour.shop/ChacourCosmeticAPI/LogoImg/TSZ4QV40BQQ291Q.jpg",
                            ProductName = "LAIT FINAL GOLD",
                            StockLevel = 100,
                            UserId = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                        },
                        new
                        {
                            ProductId = new Guid("a3977290-e3ef-4729-a98a-9919f16681d5"),
                            CategoryName = "Pommade",
                            CreateDate = new DateTime(2021, 7, 7, 17, 8, 0, 328, DateTimeKind.Local).AddTicks(8254),
                            Description = "Creme Reparateur Glutathione Carotte.",
                            Price = 8500.0,
                            ProductCode = "P0011",
                            ProductImage = "http://chacour.shop/ChacourCosmeticAPI/LogoImg/DGZEK8K2VUSTR2U.jpg",
                            ProductName = "CREME GLUTA CAROTTE",
                            StockLevel = 100,
                            UserId = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                        },
                        new
                        {
                            ProductId = new Guid("dfd02892-bce5-45f3-96c2-d9d5b6ff16cf"),
                            CategoryName = "Pommade",
                            CreateDate = new DateTime(2021, 7, 7, 17, 8, 0, 328, DateTimeKind.Local).AddTicks(8363),
                            Description = "Elegant collagene.",
                            Price = 9000.0,
                            ProductCode = "P0012",
                            ProductImage = "http://chacour.shop/ChacourCosmeticAPI/LogoImg/70JVRAFAMU0WXZB.jpg",
                            ProductName = "LAIT VIP",
                            StockLevel = 100,
                            UserId = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                        },
                        new
                        {
                            ProductId = new Guid("515b3486-70cd-4c7f-932e-111db0a9c577"),
                            CategoryName = "Pommade",
                            CreateDate = new DateTime(2021, 7, 7, 17, 8, 0, 328, DateTimeKind.Local).AddTicks(8384),
                            Description = "Concentre Reparateur Kenacol Nouveau Ultra.",
                            Price = 12000.0,
                            ProductCode = "P0013",
                            ProductImage = "http://chacour.shop/ChacourCosmeticAPI/LogoImg/EG37FXEHO1I8OKB.jpg",
                            ProductName = "CONCENTRE KENACOL",
                            StockLevel = 100,
                            UserId = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                        },
                        new
                        {
                            ProductId = new Guid("4ada21dd-e1d4-4c46-9670-76a53765f92a"),
                            CategoryName = "Pommade",
                            CreateDate = new DateTime(2021, 7, 7, 17, 8, 0, 328, DateTimeKind.Local).AddTicks(8402),
                            Description = "Eclaircissant pour le soin corporel.",
                            Price = 7000.0,
                            ProductCode = "P0014",
                            ProductImage = "http://chacour.shop/ChacourCosmeticAPI/LogoImg/CRR4LQH5O2RYINW.jpg",
                            ProductName = "GLUTATHIONE BLANC",
                            StockLevel = 100,
                            UserId = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                        },
                        new
                        {
                            ProductId = new Guid("d53cfc12-3f6c-4952-8a25-1310e440c70d"),
                            CategoryName = "Pommade",
                            CreateDate = new DateTime(2021, 7, 7, 17, 8, 0, 328, DateTimeKind.Local).AddTicks(8419),
                            Description = "Lait eclaircissant aux extrats de plantes.",
                            Price = 9000.0,
                            ProductCode = "P0015",
                            ProductImage = "http://chacour.shop/ChacourCosmeticAPI/LogoImg/2WEXJJ9C8D97NF8.jpg",
                            ProductName = "LAIT TALANGAI",
                            StockLevel = 100,
                            UserId = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                        },
                        new
                        {
                            ProductId = new Guid("837e7109-623d-4cb5-b099-69dc1ad4c90d"),
                            CategoryName = "Pommade",
                            CreateDate = new DateTime(2021, 7, 7, 17, 8, 0, 328, DateTimeKind.Local).AddTicks(8436),
                            Description = "Eclaircissant pour le soin corporel.",
                            Price = 7000.0,
                            ProductCode = "P0016",
                            ProductImage = "http://chacour.shop/ChacourCosmeticAPI/LogoImg/YWJKO17IBMHUW78.jpg",
                            ProductName = "LAIT BIOCELL KOJIC",
                            StockLevel = 100,
                            UserId = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                        },
                        new
                        {
                            ProductId = new Guid("69b64201-d151-4619-87ed-4dd0c22e191a"),
                            CategoryName = "Pommade",
                            CreateDate = new DateTime(2021, 7, 7, 17, 8, 0, 328, DateTimeKind.Local).AddTicks(8454),
                            Description = "Glutathione White Extra Fort Blue Active Intense Exclusive Advanced Lightening Whitening in 10 days.",
                            Price = 25000.0,
                            ProductCode = "P0017",
                            ProductImage = "http://chacour.shop/ChacourCosmeticAPI/LogoImg/50C1FUS1GJINVPW.jpg",
                            ProductName = "LAIT GLUTA BLEU GRAND",
                            StockLevel = 100,
                            UserId = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                        },
                        new
                        {
                            ProductId = new Guid("c6d1875e-fbd3-428f-8282-2763b15a04b3"),
                            CategoryName = "Pommade",
                            CreateDate = new DateTime(2021, 7, 7, 17, 8, 0, 328, DateTimeKind.Local).AddTicks(8485),
                            Description = "Rapid clair super eclaircissant.",
                            Price = 3000.0,
                            ProductCode = "P0018",
                            ProductImage = "http://chacour.shop/ChacourCosmeticAPI/LogoImg/VOMGSK9SRJ31LPL.jpg",
                            ProductName = "LAIT RAPIDE CLAIR",
                            StockLevel = 100,
                            UserId = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                        },
                        new
                        {
                            ProductId = new Guid("cc696134-fca7-445a-9c28-15d9738e1edd"),
                            CategoryName = "Pommade",
                            CreateDate = new DateTime(2021, 7, 7, 17, 8, 0, 328, DateTimeKind.Local).AddTicks(8502),
                            Description = "Lightening Lotion, lait de beaute eclaircissant, Hydratant et nourissant..",
                            Price = 7000.0,
                            ProductCode = "P0019",
                            ProductImage = "http://chacour.shop/ChacourCosmeticAPI/LogoImg/A3EH2X3JZZ7IEO0.jpg",
                            ProductName = "LAIT FINAL MAXITONE",
                            StockLevel = 100,
                            UserId = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                        },
                        new
                        {
                            ProductId = new Guid("866e239a-6658-4c0f-9f3b-cf0fec9c055c"),
                            CategoryName = "Pommade",
                            CreateDate = new DateTime(2021, 7, 7, 17, 8, 0, 328, DateTimeKind.Local).AddTicks(8519),
                            Description = "Concentre Glutathione Diamant Extra Fort Actif intence Eclaircissant Propriete.",
                            Price = 6000.0,
                            ProductCode = "P0020",
                            ProductImage = "http://chacour.shop/ChacourCosmeticAPI/LogoImg/DL5MEGVKMXV64KN.jpg",
                            ProductName = "CONCENTRE GLUTA NOIR",
                            StockLevel = 100,
                            UserId = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
